CREATE DATABASE SCHOOL
USE SCHOOL

CREATE TABLE STUDENTS (
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50),
    GROUPID INT FOREIGN KEY REFERENCES GROUPS(ID)  
)
 --DROP TABLE STUDENTS

CREATE TABLE GROUPS(
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50),
    ISDELETED BIT DEFAULT 0
)

--DROP TABLE GROUPS

CREATE TABLE DELETESTUDENTS (
    ID INT PRIMARY KEY,
    NAME NVARCHAR(50),
    GROUPID INT
)

INSERT INTO STUDENTS(NAME,GROUPID)
VALUES
('ELMAR',1),
('ILHAM',2),
('KENAN',1),
('CAVID',4),
('CINGIZ',5)

INSERT INTO GROUPS(NAME,ISDELETED)
VALUES
('PB302',0),
('PB101',0),
('QW45',0),
('RF6',0),
('CZ21',0)

CREATE TRIGGER TR_DeleteStudent ON dbo.STUDENTS
AFTER DELETE
AS
INSERT INTO DELETESTUDENTS(ID,NAME,GROUPID)
SELECT D.Id,D.NAME,D.GROUPID FROM DELETED AS D 
JOIN GROUPS AS G ON G.Id=D.GroupId

SELECT * FROM STUDENTS

DELETE FROM STUDENTS WHERE GROUPID=4

SELECT * FROM DELETESTUDENTS

CREATE TRIGGER TR_DELETEGROUPS
ON dbo.GROUPS 
INSTEAD OF DELETE
AS
    UPDATE dbo.GROUPS
    SET ISDELETED = 1
    FROM DELETED AS D
    WHERE GROUPS.ID = D.ID

SELECT * FROM GROUPS

DELETE FROM GROUPS WHERE ID=1

-- DROP TRIGGER TR_DELETEGROUPS